### ISSUE TITLE
When attempting ./build.sh I get this error Ubuntu 16.04

### ISSUE THREAD

**Issue by condescomputers** [Exlo84/ethopool#1]
ether1@vmi566764:~/ethopool/www$ ./build.sh
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: ethash-galaxypool -> ember-welcome-page -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: ethash-galaxypool -> ember-ajax -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: ethash-galaxypool -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: ethash-galaxypool -> ember-cli-htmlbars-inline-precompile -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: ethash-galaxypool -> ember-cli-qunit -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: ethash-galaxypool -> ember-cli-qunit -> ember-cli-test-loader -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: ethash-galaxypool -> ember-cli-test-loader -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: ethash-galaxypool -> ember-export-application-global -> ember-cli-babel
ember-cli-babel@7 (used by ember-auto-import at /home/ether1/ethopool/www/node_modules/ember-auto-import/js) cannot be used by ember-cli versions older than 2.13, you used 2.9.1
Error: ember-cli-babel@7 (used by ember-auto-import at /home/ether1/ethopool/www/node_modules/ember-auto-import/js) cannot be used by ember-cli versions older than 2.13, you used 2.9.1
    at Class.init (/home/ether1/ethopool/www/node_modules/ember-auto-import/node_modules/ember-cli-babel/index.js:40:15)
    at Class.superWrapper [as init] (/home/ether1/ethopool/www/node_modules/core-object/lib/assign-properties.js:32:18)
    at new Class (/home/ether1/ethopool/www/node_modules/core-object/core-object.js:33:38)
    at /home/ether1/ethopool/www/node_modules/ember-cli/lib/models/addons-factory.js:49:21
    at visit (/home/ether1/ethopool/www/node_modules/ember-cli/lib/utilities/DAG.js:23:3)
    at DAG.topsort (/home/ether1/ethopool/www/node_modules/ember-cli/lib/utilities/DAG.js:137:7)
    at Class.initializeAddons (/home/ether1/ethopool/www/node_modules/ember-cli/lib/models/addons-factory.js:44:11)
    at Class.initializeAddons (/home/ether1/ethopool/www/node_modules/ember-cli/lib/models/addon.js:232:38)
    at setupRegistryForEachAddon (/home/ether1/ethopool/www/node_modules/ember-cli-preprocess-registry/preprocessors.js:18:10)
    at Object.module.exports.setupRegistry (/home/ether1/ethopool/www/node_modules/ember-cli-preprocess-registry/preprocessors.js:46:3)

**Comment by condescomputers** [comment]
No comments or help?

**Comment by Exlo84** [comment]
Looks like you have updated some dependencies with breaking changes

**Comment by condescomputers** [comment]
I followed the how to in the readme step by step.
